config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :users, only: [:show]
   
  resources :items
 
  authenticated :user do
    root 'items#index', as: :authenticated_root
  end

  root 'welcome#index'

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user
  def number_days_left
    7 - (DateTime.now.to_date - created_at.to_date).to_i 
  end    
end   

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :items, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = current_user.items
  end
 
  def new
    @item = Item.new
  end
 
  def create
    @item = Item.new(item_params)    
    @item.user = current_user
    if @item.save
      redirect_to root_path, notice: 'Item saved'
    else
      flash[:alert] = 'Failure, try again'
      render :new
    end
  end

  def edit
     @item = Item.find(params[:id])
  end

  def update
     @item = Item.find(params[:id])
  
     if @item.update(item_params)
       flash[:notice] = "Item was updated successfully."
       redirect_to root_path, notice: 'Item updated'
     else
       flash.now[:alert] = "There was an error saving the item"
       render :edit
     end
   end

  def destroy
    @item = Item.find(params[:id])

    if @item.destroy
      flash[:notice] = "Item was deleted." 
    else
      flash.now[:alert] = "There was an error."
    end
    redirect_to items_path  
  end

 
  private
 
  def item_params
    params.require(:item).permit(:description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id]) 
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type.to_sym]
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade in") do 
              concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
              concat message 
            end)
    end
    nil
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_form.html.erb
<%= form_for @item do |f| %>
  <div class='form-group'>
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>
    <%= f.submit %>
<% end %>

app/views/items/edit.html.erb
<h1>Edit Item</h1>
<%= render 'form' %>

app/views/items/index.html.erb
<h1>Items</h1>
<%= link_to 'New item', new_item_path, class: 'btn btn-default'  %>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Description</th>
      <th>Days Left</th>
      <th>Mark Complete</th>    
      <th>Edit Item</th>
    </tr>
  </thead>
  <tbody>
      <% @items.each do |item| %> 
        <tr>
          <td><%= item.description %></td>
          <td><%= item.number_days_left %></td>
          <td><%= link_to "", item, method: :delete, class: 'glyphicon glyphicon-ok' %></td>
          <td><%= link_to "Edit", edit_item_path(item) %></td>
        </tr>
      <% end %> 
     
   </tbody>   
</table>
   

app/views/items/new.html.erb
<h1>New Item</h1>
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocitoff</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <div class="row">
      <div class="col-md-8">
        <ul class="nav">
          <li><%= link_to "Home", root_path %></li>
        </ul>
      </div>

      <div class="col-md-4">
        <div class="auth-links text-right">
          <% if user_signed_in? %>
            Signed in as: <strong><%= current_user.email %></strong> |
            <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
            <%= link_to 'Profile', user_path(current_user) %>
          <% else %>
            <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
            <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
          <% end %>
        </div>
      </div>
    </div>
    <%= flash_messages %>
    <%= yield %>
  </div>


</body>
</html>

app/views/users/show.html.erb
<h3>User Profile</h3>
<p>Email: <%= @user.email %></p>
<%= link_to 'Home', root_path %>

app/views/welcome/index.html.erb
<h1>Welcome to Blocitoff</h1>
<p>Please see the list of groceries below</p>